[package]
name = "task-changes"
version = "0.1.0"
authors = ["ayosec@gmail.com"]
edition = "2018"

[dependencies]
memchr = "2.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
